version: '3'

services:

  proxy:
    build: ./proxy
    restart: always
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443

  site:
    build: ./site
    restart: always
    # TODO(lamuguo): Disable export and ports below.
    # expose:
    #  - 8080
    #ports:
    #  - 8080:80
      
    
